# Generated by Django 4.0.4 on 2022-05-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
